query InvocationTreeFlow($invocationId: uuid!) {
  invocations_by_pk(id: $invocationId) {
    ...invocationTree
    correlated_invocations(order_by: {created_at: asc}) {
      ...invocationTree
    }
  }
}

fragment invocationTree on invocations {
  id
  source_event_id
  source_function
  status
  total_duration_ms
  correlation_id
  source_job_id
  created_at
  updated_at

  source_job_execution {
    id
    job_name
    job_function_name
    status
    duration_ms
    correlation_id
    created_at
    updated_at
  }

  event_executions {
    id
    event_name
    detected
    status
    detection_duration_ms
    handler_duration_ms
    correlation_id
    created_at
    updated_at

    job_executions {
      id
      job_name
      job_function_name
      status
      duration_ms
      result
      error_message
      correlation_id
      created_at
      updated_at

      # Jobs that trigger new invocations
      triggered_invocations {
        id
        correlation_id
      }
    }
  }
}